name: Release

on:
  push:
    branches: [master, alpha, beta, next]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          npx -p semantic-release \
              -p @semantic-release/changelog \
              -p @semantic-release/git \
              semantic-release
